config/routes.rb
Rails.application.routes.draw do

  resources :photos
  resources :users
  resources :products
  get 'varieties/:product', to: 'varieties#index'
  resources :varieties

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'gallery#index'

  get 'gallery/show/:id', to: 'gallery#show'
  match '(/:name1(/:name2(/:name3)))', to: 'gallery#index', via: :get
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :variety
  delegate :product, :to => :variety # eq to: has_one :product, :through => :variety
  belongs_to :place

  mount_uploader :path, PhotoUploader

  validates_presence_of :path

  self.per_page = 8

  def product
    self.variety.product unless variety.blank?
  end

  def product=(val)

  end

  def self.find_all(product, variety, place)
    photos = Photo.all
    photos = product.photos if !product.blank?
    photos = photos.where(variety: variety) if !variety.blank?
    photos = photos.where(place: place) if !place.blank?
    return photos
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :get_list_info,  except: [:index, :show]
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_photo_params, except:  [:index, :show]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    # todo: get current user to affect to the added photo
    @photo.user = User.find(1)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def set_photo_params
      if !@photo.blank?
        @product = @photo.product
        @product_id = @product.id
        @varieties = @product.varieties.pluck('name, id')
        @variety_id = @photo.variety.id
        @place_code = @photo.place.place_code
        return
      end
      if !params[:product].blank?
        @product = Product.find_by_id(params[:product])
        @product_id = @product.id unless @product.blank?
        @varieties = @product.varieties.pluck('name, id') unless @product.blank?
      end
      if !params[:photo].blank?
        @variety_id = params[:photo][:variety_id]
        @place_code = params[:photo][:place_id]
      end
    end

    def get_list_info
      #todo: use product_code, variety_code, and place_code to hide the ID from the user
      @products = Product.all.pluck('name, id')
      @varieties = Variety.all.pluck('name, id')
      @places = Place.all.pluck('name, id')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:path, :variety_id, :place_id, :date, :published, :product)
    end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.slim
= form_for(photo) do |f|
  - if photo.errors.any?
    #error_explanation
      h2
        = pluralize(photo.errors.count, 'error')
        prohibited this photo from being saved:

      ul
        - photo.errors.full_messages.each do |message|
          li= message

  .field
    = f.label :file
    = f.file_field :path

  .field
    = f.label :product
    select[name="product" id="product" class="selectors" onclick="photos.events.product_changed()"]
      option[value=""] - All -
      = options_for_select(@products, selected: @product_id)

  .field
    = f.label :variety_id
    = f.select :variety_id, @varieties, {:selected => @variety_id, :prompt => '- select -'}, id: 'varieties'

  .field
    = f.label :place_id
    = f.select :place_id, @places, {:selected => @place_code, :prompt => '- select -'}

  .field
    = f.label :date
    = f.datetime_select :date, :discard_hour => true

  .field
    = f.label :published
    = f.check_box :published

  .actions
    = f.submit

app/views/photos/edit.html.slim
h1 Editing Photo

= render 'form', photo: @photo

=> link_to 'Show', @photo
| |
=< link_to 'Back', photos_path

app/views/photos/index.html.slim
p[id="notice"] = notice

h1 Photos

table
  thead
    tr
      th ID
      th Path
      th Product
      th Variety
      th Place
      th User
      th Date
      th Published
      th[colspan="3"]
  tbody
    - @photos.each do |photo|
      tr
        td = photo.id
        td = image_tag photo.path.thumb.url, size: 80
        td = photo.product.product_code
        td = photo.variety.variety_code
        td = photo.place.name
        td = photo.user.username
        td = photo.date
        td = photo.published
        td = link_to 'Show', photo
        td = link_to 'Edit', edit_photo_path(photo)
        td = link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }

br

= link_to 'New Photo', new_photo_path

app/views/photos/new.html.slim
h1 New Photo

= render 'form', photo: @photo

= link_to 'Back', photos_path

app/views/photos/show.html.slim
p[id="notice"] = notice

p
  =< image_tag @photo.path.normal.url, size: '1200x900'

p
  strong Product:
  =< @photo.product.product_code

p
  strong Variety:
  =< @photo.variety.variety_code

p
  strong Place:
  =< @photo.place.name

p
  strong User:
  =< @photo.user.username

p
  strong Date:
  =< @photo.date

p
  strong Published:
  =< @photo.published

=> link_to 'Edit', edit_photo_path(@photo)
| |
=< link_to 'Back', photos_path